language: python
dist: xenial
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - 3.7
 - 3.6

install:
 - pip install -U pip
 - pip install -U black flake8
 - pip install -U -r requirements.txt

script:

 # Dry run
 - python lunchbot.py --dry-run

 # Static analysis
 - flake8 --statistics --count
 - black --py36 --check --diff .

matrix:
  fast_finish: true
