language: python
dist: xenial
cache: pip

python:
 - 3.8
 - 3.7
 - 3.6

install:
 - pip install -U pip
 - pip install -U black flake8 pre-commit
 - pip install -U -r requirements.txt

script:

 # Dry run
 - python lunchbot.py --dry-run --json

 # Static analysis
 - pre-commit run --all-files

matrix:
  fast_finish: true
