language: python

cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy
 - 2.7
 - 3.6
 - 3.5
 - 3.4
 - 3.3

sudo: false

install:
 # Speedup for CI: http://lxml.de/installation.html#installation
 - CFLAGS=-O0 pip install lxml
 - pip install BeautifulSoup4 slacker-cli
 - pip install pep8 pyflakes

script:

 # Dry run
 - python lunchbot.py --dry-run

 # Static analysis
 - pyflakes .
 - pep8 --statistics --count .

matrix:
  fast_finish: true
