language: python

dist: trusty
sudo: false

cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - 2.7
 - 3.6
 - 3.5
 - 3.4
 - 3.3

install:
 - pip install -r requirements.txt
 - pip install pep8 pyflakes

script:

 # Dry run
 - python lunchbot.py --dry-run

 # Static analysis
 - pyflakes .
 - pep8 --statistics --count .

matrix:
  fast_finish: true
